[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["idenrai <geniuskwon966@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
duckdb = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
